### ISSUE TITLE
Help with customizing the card

### ISSUE THREAD

**Issue by corvy** [tmjo/charger-card#23]
Hello! Thanks for this great addition to Home Assistant. I am struggling to understand how the card is customized. I am trying to do the following:

- compact
- remove sitename (and preferrable the '-' hyphen before the chargername
- customize the text for statuses (they are too long on mobile device screens)

Here is my card setup. The only achievement I made is compact mode.... :O 

```
  - type: 'custom:charger-card'
    brand: easee
    entity: sensor.lader1_status
    chargerImage: Black
    details:
      name:
        entity_id: sensor.lader1_status
        attribute: site_name
      statetext:
        disconnected: "Frakoblet"
        awaiting_start: "Avventer Start"
        charging: "Lader"
        completed: "Fullført"
        error: "Feil"
        ready_to_charge: "Klar for Lading"
    compact_view: true
    show_collapsibles: true
```

Sorry if this the wrong place to ask. If at all I would like to get some examples in the doc so I could more easily understand.

**Comment by tmjo** [comment]
Hi,

The customizing of status text is a feature, but there has been reported some other issues that might indicate a bug in this option. I will fix it when I get time.

For the compact view, this should be available as a toggle switch in the UI configuration, or you can add this in manual config:
`
compact_view: true
`
It seems to be working on my test at least. I see you have added it as well, but it doesn't work? 

For customizing name and sitename, including removing the hyphen you should be able to tweak around with:

```
  name:
    entity_id: sensor.easee_1_status
    attribute: name
  location:
    entity_id: sensor.easee_1_status
    attribute: site_name
```

As I recall, there is a feature for removing the hyphen if only one of them is added and it seems to be working like this on a quick test I did in my setup. Since you have only added one it should be like this, so it seems strange it.

Are you on the latest version of the card?

**Comment by corvy** [comment]
Thanks for the response! 

I am running version 0.9.42 installed with HACS. Just tried, for fun, this config:

```
  - type: 'custom:charger-card'
    brand: easee
    entity: sensor.eneren_status
    chargerImage: Black
    details:
      location:
        entity_id: sensor.eneren_status
        attribute: name
      name:
        entity_id: sensor.eneren_status
        attribute: name
      statetext:
        disconnected: "Frakoblet"
        awaiting_start: "Avventer Start"
        charging: "Lader"
        completed: "Fullført"
        error: "Feil"
        ready_to_charge: "Klar for Lading"
    compact_view: true
    show_collapsibles: true   
```

This should in theory make site-name and name the same. But it does not change anything. It stille uses site-name + charger name. Also tried to toggle between compact and full mode. The same problem is on both.

**Comment by corvy** [comment]
Sorry I see I quoted the version of the Easee Hass integration version. I am on 0.0.14 of the charger-card.

**Comment by tmjo** [comment]
Aha, that's an old version. Or in fact it is only partly the truth, because it is actually the latest official release. However, the documentation reflects the latest release 0.1.1 which is only released as pre-release candidate (available in HACS if you enable "Show beta versions". 

I'll try to find time to release it officially soon though!

**Comment by corvy** [comment]
Trying the new version now, at least I am getting further now. But what is #SERVICEVAL# ? I cannot understand what it relates to. I am guessing the CHARGERID is the serialnumber. Am I right?

**Comment by tmjo** [comment]
You should leave #SERVICEVAL# as it is, it something the card looks for and replaces with for instance 5A if that is what was selected for the service. So there is some kind of 'magic' going on there. Typically for the amp dropdowns, the selected value is put in as a value instead of #SERVICEVAL#

More or less the same with CHARGERID, but this is replaced during configuration of the card. If doing it manually, it should be replaced with the charger id that is found as an attribute for the status sensor (typically EHxxyyzz). This is the case for Easee chargers, but the whole point is that it is fully customizable, so it all depends on what your service call needs which again depends on each integration.

**Comment by corvy** [comment]
I am getting there slowly. Trying to simplify for better WAF :) 

<img width="397" alt="image" src="https://user-images.githubusercontent.com/138292/170469486-bfcb7a77-c273-4aae-9339-1b49779a0d8c.png">

Is it possible to change the "on" text for "kabellås" and the smart_charging icon above it to be switches that could be toggled directly on the card? Or at minimum replace "on" with "på" for example. Any ideas?

**Comment by tmjo** [comment]
Having a switch directly is not something I will spend time to implement since it changes the way the card works fundamentally. However, it should be fairly easy to implement a service for unlocking and pin it to a custom button on the bottom toolbar if that suits your needs?

About the "on" vs "på", I see that for some reason it is not translating. I was expecting it to use the language chosen in HA, but for some reason it doesn't. Will look into it.

**Comment by corvy** [comment]
Thanks, yeah I agree to both suggestions. Getting a service button to toggle would work great. Thanks again! 👍

**Comment by tmjo** [comment]
Please test alpha-version v0.2.0-alpha released now. It should fix UI, but please test carefully.

It should (hopefully) fix on/på and off/av as requested.

**Comment by corvy** [comment]
This works now 😊 thank you!
