### ISSUE TITLE
"click for limits"-options display faulty

### ISSUE THREAD

**Issue by LuckyTriple7** [tmjo/charger-card#26]
Card is working good, but the "click for limits" Option is faulty:

![image](https://user-images.githubusercontent.com/60685158/178657319-bc8582d8-a0e3-43d3-91a0-f07c72161e88.png)

The options are displayed vertically but should be horizontal. Also, not all options are visible.

**Comment by tmjo** [comment]
Hi and thanks for reporting. Yes, I am aware. There's been a problem with the dropdown list since [HA deprecated the paper version of dropdown](https://developers.home-assistant.io/blog/2022/02/18/paper-elements?_highlight=paper). I tried to do some quick fixes, but it took some time and I wasn't able to complete it before being swallowed by other tasks. I will dig into it eventually, and if anyone sees a quickfix, please contribute.

**Comment by bartwybouw** [comment]
Hi, first of all a *B I G* thank you for your work!!! (and you have a large coffee coming your way).
I'm also not able to update the limits list (6-8-10-12-etc.) using the config file.

**Comment by blackbird0589** [comment]
Hi tmjo,
do you already have had time to look for a solution for this bug?

kind regards

**Comment by tmjo** [comment]
Hi, it is close. I've rewritten everything to typescript instead of plain javascript, so it will hopefully fix all known issues (but probably introduce some new ones, so need a bit more time for testing).

**Comment by tmjo** [comment]
Please test alpha-version v0.2.0-alpha released now. It should fix UI, but please test carefully.

**Comment by blackbird0589** [comment]
Hi tmjo,
just tested v0.2.2-alpha. Drop-Down feature now works perfekt for me!
I've two different Limits and the menu appears on click right above the used key.

![image](https://user-images.githubusercontent.com/97593051/220946403-1d6875e7-8535-465a-8b90-65cf24ea8a26.png)

Thank you very much for the solution and your time!

**Comment by tmjo** [comment]
Sounds great! I'll close the issue, please feel free to create a new one if you find any other bugs.
