### ISSUE TITLE
Charger card vanished..

### ISSUE THREAD

**Issue by finalbillybong** [tmjo/charger-card#44]
I've been using this card with my Zappi charger for months but today the card is not showing up on MS Edge, iOS Safari and iOS HA app. It is still showing fine on my Android HA app though. I have been troubleshooting this for hours with no success. 

Here is my yaml that has been working fine for months. 
https://pastebin.com/6dQ7VtkS

**Comment by tmjo** [comment]
Hi, that sounds strange. Since it is showing on mobile app, it leads me to assume there is a caching issue (i.e. try hard reload CTRL+F5), but on the other hand it shouldn't be if you've tried in several different browsers.

Please take a look at your entities, see if anything is missing in one or several of them. Perhaps there is a bug in the card making it not render due to some problem. You should also open developer tools (CTRL+SHIFT+I) and look for any error messsages.

**Comment by finalbillybong** [comment]
Hi thanks for the response.

it is working on Android app but not iOS app.

I have already tried clearing browser cache (sorry should have mentioned that in the OP). I’ll have a look at entities as suggested but I did have a quick glance over them already and couldn’t see an issue.

**Comment by finalbillybong** [comment]
> Hi, that sounds strange. Since it is showing on mobile app, it leads me to assume there is a caching issue (i.e. try hard reload CTRL+F5), but on the other hand it shouldn't be if you've tried in several different browsers.
> 
> Please take a look at your entities, see if anything is missing in one or several of them. Perhaps there is a bug in the card making it not render due to some problem. You should also open developer tools (CTRL+SHIFT+I) and look for any error messsages.

It has now vanished from the Android HA app too. So weird.

**Comment by finalbillybong** [comment]
I figured this out. For some reason the card didnt like having 3 entities under 'info_right:'. I removed one of them and the card works again now.
