### ISSUE TITLE
en-GB Translation

### ISSUE THREAD

**Issue by codeclinic** [tmjo/charger-card#52]
Just saw this changelog on the latest release:

_Fix en-GB translation that was always present but not working (as opposed to regular en)._

en-GB by virtue of being the original English (from England) literally is "regular en" and therefore all other "English" varieties are the deviants and not vice-versa.

**Comment by tmjo** [comment]
Don't disagree with you there, but for some reason en-GB exists in HA? 

![image](https://github.com/tmjo/charger-card/assets/54450177/cc784ad0-e431-42b4-876b-425e7bb6ee18)

I just saw this difference because I had one environment setup with "English" and another in "English (GB)" in HA where the latter did not translate at all. If I remember correctly, before HA got support for specifying time format (24h) and number format separately, I think the advice was to choose GB, so I think that's why I put my device to English GB. My native language is Norwegian, but I prefer to have all my devices in English language even though I can't stand imperial units and AM/PM for time. Me about that. :)

My en.json and en-GB.json files are the same though, feel free to correct the English though :)

Cheers!

**Comment by purcell-lab** [comment]
I have proposed some very minor changes for en_GB. https://github.com/tmjo/charger-card/pull/53

Myself I use en_AU, which has en_GB spelling, but uses the metric system and supports 24 hour time.

**Comment by tmjo** [comment]
Jolly good, thanks!

**Comment by tmjo** [comment]
Really sorry for the delay, but finally it is updated in v0.2.7
