### ISSUE TITLE
Session Energy doesn't show correct value

### ISSUE THREAD

**Issue by slashbv** [tmjo/charger-card#9]
The correct value as shown in easee.cloud is 1.9kWh but the card shows 1937 kWh. It should probably show 1.937 kWh. However I it seems also the sensor itself doesn't show correct value. It shows 1.937 Wh no matter if I check or uncheck kWh to Wh checkbox in configuration. Also if the car is not connected shouldn't this be 0 ?
![image](https://user-images.githubusercontent.com/59421121/123278780-8652e900-d507-11eb-8e7c-53ee9ad1f063.png)
![image](https://user-images.githubusercontent.com/59421121/123278840-95399b80-d507-11eb-9705-0fbc04fee717.png)
![image](https://user-images.githubusercontent.com/59421121/123278816-8d79f700-d507-11eb-99d2-67b3cf68f505.png)

It is the same situation for Lifetime Energy.

**Comment by tmjo** [comment]
I'll check the scaling. I remember that it is not working perfect in the integration when changing between the units, it typically worked best when removing and adding the integration and applying what one want in the first place. But I also think the card is not adapted for Wh, so I'll check that.

Session energy is reset by Easee, so nothing we can do there. I believe it is reset upon next connection or something. If I recall correctly mine reports session energy when I'm away and until I reconnect. Here's mine and I'm still not at home:
![image](https://user-images.githubusercontent.com/54450177/123280381-0463bf80-d509-11eb-9f67-8605beb22baa.png)

This has annoyed me since I use it to send a Telegram message to my phone each morning with charging energy during the night, but if I wasn't driving the day before it keeps same value as day before. A workaround for this may be to setup a [utility meter](https://www.home-assistant.io/integrations/utility_meter/) counting the lifetime energy and have HA reset it every night (daily).

**Comment by slashbv** [comment]
It is clear now. I have removed the integration and added back and all seems to be fine. I will close the ticket. Thanks!
